### ISSUE TITLE
Errors fixed: Here is how to use the plugin

### ISSUE THREAD

**Issue by imeDevelopers** [EddieKamau/ussd_advanced#21]
in your pubspec.yaml file use the dependency as follow:

```
 ussd_advanced: #^1.1.0
   git:
     url: https://github.com/jgithaiga/ussd_advanced.git
     ref: master
```

the [jgithaiga fork](https://github.com/jgithaiga/ussd_advanced) is better and fixed errors.
